return {
  "catppuccin/nvim",
  name = "catppuccin",
  priority = 1000,
  config = function()
    require("catppuccin").setup({
      flavour = "mocha",
      background = {
        light = "latte",
        dark = "mocha",
      },
      transparent_background = false,
      show_end_of_buffer = false,
      term_colors = true,
      dim_inactive = {
        enabled = false,
        shade = "dark",
        percentage = 0.15,
      },
      no_italic = false,
      no_bold = false,
      no_underline = false,
      styles = {
        comments = { "italic" },
        conditionals = { "italic" },
        loops = {},
        functions = {},
        keywords = {},
        strings = {},
        variables = {},
        numbers = {},
        booleans = {},
        properties = {},
        types = {},
        operators = {},
      },
      color_overrides = {},
      custom_highlights = function(colors)
        return {
          NormalFloat = { bg = colors.mantle },
          FloatBorder = { bg = colors.mantle, fg = colors.mantle },
          VertSplit = { bg = colors.base, fg = colors.surface1 },
          CursorLineNr = { fg = colors.yellow, bold = true },
          LineNr = { fg = colors.overlay1 },
          Comment = { fg = colors.overlay1, italic = true },
          ["@comment"] = { fg = colors.overlay1, italic = true },
        }
      end,
      integrations = {
        alpha = true,
        cmp = true,
        dap = true,
        dashboard = true,
        gitsigns = true,
        telescope = true,
        treesitter = true,
        which_key = true,
        harpoon = true,
        indent_blankline = { enabled = true },
        lsp_trouble = true,
        markdown = true,
        mason = true,
        neotree = true,
        noice = true,
        notify = true,
        semantic_tokens = true,
        snacks = true,
        treesitter_context = true,
        rainbow_delimiters = true,
      },
    })

    vim.cmd.colorscheme("catppuccin")
  end,
}